version: '3.0'
services:
  wiremock:
    image: wiremock/wiremock
    ports: 
      - '8090:8080'
  s3-mock:
    image: adobe/s3mock
    ports:
      - 9090:9090
    environment:
      - initialBuckets=node-user-reports
