name: Build and test

on: push

env:
  GITHUB_CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: "1.21"
    - name: Build Binary
      run: go run mage.go -v build
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: "1.21"
    - name: Run unit tests
      run: go run mage.go -v test
  e2e:
    name: Run e2e scenarios
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin || true
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: "1.21"
    - name: Run e2e scenarios
      run: go run mage.go -v e2e

